### ISSUE TITLE
C/C++ syntax highlighting

### ISSUE THREAD

**Issue by sonictk** [x13pixels/remedybg-issues#116]
Not sure if this has actually been requested by anyone, but it would be nice to be at least able to highlight the standard keywords used in C/C++ in the source file window so that it's easier to identify areas of the code. Having everything be one colour makes a little hard to read code sometimes.

**Comment by anaymsinha** [comment]
It is doable and also a nice idea.

**Comment by x13pixels** [comment]
It has been asked for but I don't see it written up anywhere. Thanks for doing so.

**Comment by kmar** [comment]
there's already an ImGUI component for this: [https://github.com/BalazsJako/ImGuiColorTextEdit](url)

**Comment by dbechrd** [comment]
This is pretty much the only reason I don't use RemedyBG wayyyyyyyyyy more often. I love it, but I can't read my code as a gray blob. Even a simple, toned down colorscheme like Casey's 4Coder theme would improve readability 100x.

![image](https://user-images.githubusercontent.com/707367/199537139-0d2b7971-84d7-4110-a060-bf0f130ba44d.png)

**Comment by Chinayang1** [comment]
How about GNU Emacs's  Face mechanism that allow user to choose color for different kinds of word of  programming language?

**Comment by x13pixels** [comment]
@ryuukk Apologies for the lack of progress on this. I don't use syntax highlighting but I understand that it is a useful feature to have when viewing code for many people. The library you pointed to in the previous comment was used as the basis for the text view in RemedyBG long ago. However, it has been largely gutted due to performance (and other) issues (like failing to syntax highlight properly). From the project's readme:
 > syntax highligthing of most languages - except C/C++ - is based on std::regex, which is diasppointingly slow..

I did intentionally note that syntax highlighting is not available in the project's page:
> This project is in development and should be considered in "early access". There are certainly bugs as well as features on the roadmap. For example, the text window for displaying source code does not currently have any sort of syntax highlighting, although this planned for a future version.

Perhaps I incorrectly chose which features to work on in my limited time over the years (I'd much rather write a debugger than a text editor) and I, again, apologize for not getting to this sooner.

Anyway, happy to refund your money given viewing colorized text is an important feature for you and has not been implemented yet.

**Comment by n00bmind** [comment]
I've been reading up about the tree-sitter lib lately (https://tree-sitter.github.io/tree-sitter/), and it seems like a pretty capable thing. I haven't tried anything with it myself, so I cannot speak about how hefty of a dependency it is or how easy to use it is in practice, but what I gather from other people is that it at least looks _decent_.
Anyway, just an idea..

**Comment by kevyuu** [comment]
Yeah, I would second tree-sitter recommendation. It should be faster and more accurate than regex. I really wish this feature exist.

**Comment by x13pixels** [comment]
Thanks for the suggestion @n00bmind. I'll take a look.

**Comment by x13pixels** [comment]
Doesn't look like tree-sitter is going to work out at this time. For example,

- v0.20.7: example program hangs: https://github.com/tree-sitter/tree-sitter/issues/2782
- assignment in conditions can be parsed by c parser but not c++: https://github.com/tree-sitter/tree-sitter-cpp/issues/212
- etc.

**Comment by kmar** [comment]
ok, I've just open sourced my very simple highlighter (header only), it can be found here along with an example,
it doesn't use regexes
the link is here: [https://github.com/kmar/syntax_highlight](https://github.com/kmar/syntax_highlight)

it requires C++17 because of std::string_view, but well...
I use it in my private text editor, so it's battle-tested (except I don't use stl in my framework at all)

**Comment by x13pixels** [comment]
Implemented comment / keyword highlighting.

To ship in 0.3.9.7.
