### ISSUE TITLE
Re-attach to process

### ISSUE THREAD

**Issue by sonictk** [x13pixels/remedybg-issues#149]
I actually haven't seen this requested yet, but I was wondering if this is a low-hanging fruit feature that could be implemented. In VS, when I'm debugging plug-ins in 3rd-party applications, I make use of this feature heavily, and it's always a drag having to find the application in the list of open processes to attach to. Could there be a simple "Re-attach to process" function in the same vein as Visual Studio's one, where it just attaches to the last executable that was attached previously? This would improve usability quite a lot, I think, for people that have to debug 3rd-party applications where the attach workflow works better.

Thanks!

**Comment by x13pixels** [comment]
@sonictk Rather late but I thought I'd mention it anyway. I bumped into a case where "Reattach to Process" does not always work. Specifically, if the "Attach" button was clicked rather than double-clicking on a process in the Attach dialog. Super sorry I didn't catch this before as I remember you having issues with this feature!

A fix for this will be in the upcoming patch release 0.3.5.1.
