### ISSUE TITLE
C99 Variable Length Arrays (VLA) cannot be watched

### ISSUE THREAD

**Issue by ghost** [x13pixels/remedybg-issues#174]
VLA memory doesn't show up properly when inspected in watch window. After initialization, VLAs are show as unreadable memory.
![Capture](https://user-images.githubusercontent.com/47712859/95108261-57a79f00-073b-11eb-8c95-a4671411b27e.PNG)

**Comment by x13pixels** [comment]
I was able to duplicate incorrect behavior for VLAs using with Clang 10.0.0 and workaround using `*available_layers, 7` instead of `available_layers, 7`.

I'll need to update to a later version of the CL compiler to test it (16.5 doesn't support VLAs but supposedly 16.8 does).

In either case, I'll get this fixed.

Thanks.

**Comment by x13pixels** [comment]
Doesn't look like Visual Studio 16.8 supports VLAs either. Can you please confirm you are using Clang? If so, what version?

Thanks!

**Comment by ghost** [comment]
I don't think visual studio will support VLA in the near future, their priority is C++ and VLA's are not part of the C++ standard. Anyway, I am using clang 10.0.0 .
Thanks you for your work !

**Comment by x13pixels** [comment]
Fixed handling of VLAs.

![image](https://user-images.githubusercontent.com/3690363/96356465-f083d600-10bc-11eb-8196-247382f4d181.png)
