### ISSUE TITLE
Oddities with the disassembly view

### ISSUE THREAD

**Issue by sonictk** [x13pixels/remedybg-issues#234]
I have noticed that sometimes, there are some applications that when debugged in RemedyBG, the source file window allows me to step normally and so does the disassembly window separately, but both won't step "together", and there is no yellow arrow in the disassembly window showing me what/where exactly I'm stepping to. 

- If there could be a "navigate to current line of execution" button or something available in general, it would help me at least figure out "where I am" in the current execution without having to execute a step operation (since I also have no idea when I step in the disassembly window where I am at this point)
- If we could also copy values from the registers window, I could at least copy the value of RIP to the disassembly window and paste it there. However, this is blocked by the next problem, which is:
- Ctrl-G in the disassembly window also seems broken for me; no matter what address I type in there (even if it's an address that it shows me in the same window), after I hit Enter, it doesn't scroll the view to bring that address into view.

I haven't quite figured out under what circumstances this association breaks with a minimal sample and the disassembly window no longer steps "in sync" with the source file window, but I can definitely reproduce this with 100% reliability on a certain application. Is there any specific thing I can try on my end to figure this out? Under what circumstances is disassembly/source relationship lost? (i.e. even clicking around on different frames in the call stack window doesn't navigate the disassembly view around, though it does for the source file)

UPDATE: I'm a little busy at work and haven't had time to make a minimal repro example, but here's at least a screenshot of the problem manifesting in action. When this happens, clicking around stack frames never navigates the disassembly window away from its current position, and neither does inserting the address of RIP directly:

![image](https://user-images.githubusercontent.com/2504199/162314581-ec177542-6a51-4be3-8e66-ca3d1c844487.png)

There's also times where the entire disassembly just...disappears. And nothing I do will get it back:
![image](https://user-images.githubusercontent.com/2504199/163262550-1026bd92-42b4-480c-9d0c-9c4ecead4bb3.png)

EDIT: I have found that this occurs pretty much almost always when debugging `UnrealEditor`, and I'm wondering if it's just some weird issue that occurs. Not sure if you have the patience to build and debug Unreal, but I couldn't figure out a minimal repro case for this, unfortunately.

**Comment by sonictk** [comment]
Ok, after a long while, I took some time to investigate this.

This doesn't occur in Unreal Development/Shipping builds; the disassembly shows up fine and I can step through it. Which implies a problem with the compilation options in Debug builds. (Just to confirm; I tried deleting the PDB file generated and the same issue occurs, which makes sense since it doesn't seem likely you would be using the PDB file for anything related to the disassembly view)

I found that the issue is that in debug builds, we can still compile with `/Ob2` even though we also pass `/Od`. This somehow triggers the aforementioned bug in RemedyBG. (We set this option in `VCToolChain.cs`, if you have a copy of the Unreal source available.) If I override this to be `/Ob0`, the issue disappears.

This problem doesn't occur with Visual Studio or WinDbg, so I assume this inline expansion somehow is triggering a bug in how RemedyBG determines the disassembly in debug builds.

Hopefully this helps in narrowing down and reproducing the issue!

**Comment by x13pixels** [comment]
Thanks! This is due to how RemedyBG linearly scans the code segment and records known ranges of valid instructions. It uses this to disassemble chunks of instructions for the disassembly window. There must be something in the /Ob2 codegen that is tripping this up. This needs to be augmented with the debug information, when available, or add more robust handling of invalid sequences, or replace this algorithm to eliminate the need for scanning altogether.

**Comment by rivten** [comment]
Hello ! Thanks a lot for your work on Remedy !
Just wanted to chime in because I've been hitting the same kind of issues, with some similarities as well as some differences.

Similarities:
- I am also on Unreal Engine
- It seems only to happen to file compiled with `/Od`, at least it only appears on file that I've touched recently, and that ends up in the unity adaptive build (I tried playing with this parameters but with no success).
- Source / disassembly relationship is lost as well.

Differences:
- I've played a lot with the `/Ob2` parameters, @sonictk comment were a great help to make me understand the build system in Unreal actually, but even though I've configured the build so that no more `/Ob2` flag is put in the command line (which I saw because the build process outputs the final `cl.exe` parameters), I seem to still repro the issue.

What I can also say:
- I'd be happy to share anymore info about the build even though I can't give any specifics about the project.

**Comment by sonictk** [comment]
@rivten Try also making sure that in `VCToolChain.cs` you disable passing `/Os` and also force `/Ob0` to be passed. I actually recently committed a change into UE5's source that will fix this under Clang compilation but I think we still force it on for MSVC by default. RemedyBG should really be able to handle this regardless though, so I think leaving this bug report open is still valid.

**Comment by x13pixels** [comment]
This should be addressed in 0.3.9.6. Leaving this issue open until I am able to confirm.

**Comment by x13pixels** [comment]
Fairly certain the reported problem was fixed in 0.3.9.6 as mentioned. Closing this issue.
