### ISSUE TITLE
RemedyBG dies when stack overflows

### ISSUE THREAD

**Issue by JustSlavic** [x13pixels/remedybg-issues#248]
Before dying it shows that exception was thrown:

![image](https://user-images.githubusercontent.com/26839955/172063994-71396e8e-88ac-463d-aa21-181fc843fb42.png)

Although it's not a big deal because the startup time is so low, but I doubt it's intended behaviour.

**Comment by x13pixels** [comment]
@JustSlavic If possible, could you please send a crash dump that duplicates this? Can capture a DMP by running RemedyBG under procdump with: `procdump.exe -ma -e -x . remedybg.exe`. I understand if this is not feasible.

Asking because I'm not seeing a crash in any of the stack overflow tests I have.

![image](https://user-images.githubusercontent.com/3690363/172515900-168252ee-cbe7-4a1f-9bb6-13687a852f20.png)

**Comment by JustSlavic** [comment]
Yes, of course! The only problem, I cannot attach it here nor push into my repo, because it exceeds github's 100Mb filesize cap. It weights ~400Mb. Is it ok if I ask you to download it from Google Disk? Here's the link: https://drive.google.com/file/d/1ukx83c46mh2gTOB0WKUcTU7bfHjMWmkC/view?usp=sharing

If this hepls:
Remedybg version: 0_3_7_1
Full code on which I recorded crash dump:
```c++
int stop_recursion = 0;
void foo() {
    if (stop_recursion) {
        return;
    }

    foo();
}

int main() {
    foo();
    return 0;
}
```
Built with `cl crash.cpp /Fecrash`
Compiler version: `Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30133 for x64`

**Comment by x13pixels** [comment]
[0.3.8.0] Fixed crash caused when using a watch expression with relative scope when the stack overflows (e.g., `{*}game_state`).
